name: Deploy GitHub Pages

on: 
  workflow_run:
    workflows: ['Run Unit Tests']
    types: ['completed']

  workflow_dispatch:
    inputs:
      page-root-directory:
        description: Page root directory
        default: './dist/'
        type: string

permissions:
  contents: read
  pages: write
  checks: write
  id-token: write

jobs:
  deploy:
    name: Deploy Page
    env:
      page-root-directory: './dist/'
      deno-version: v1.x

    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Deno (${{env.deno-version}})
      uses: denoland/setup-deno@v1.1.4
      with:
        deno-version: ${{env.deno-version}}
  
    - name: Build
      run: deno task build

    - name: Setup Pages
      uses: actions/configure-pages@v4

    - name: Upload artifact (Automatic)
      if: (!github.event.inputs.page-root-directory)
      uses: actions/upload-pages-artifact@v3
      with:
        path: ${{env.page-root-directory}}

    - name: Upload artifact (Workflow Dispatch)
      if: (github.event.inputs.page-root-directory)
      uses: actions/upload-pages-artifact@v3
      with:
        path: ${{github.event.inputs.page-root-directory}}

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
