name: Run Unit Tests

on:
  push:
    branches: ["main"]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  checks: write

jobs:
  test:
    name: Unit Test
    runs-on: ubuntu-latest
    env:
      deno-version: v1.x

    steps:
      - name: Setup Repository (${{github.event.repository.name}})
        uses: actions/checkout@v4

      - name: Setup Deno (${{env.deno-version}})
        uses: denoland/setup-deno@v1.1.4
        with:
          deno-version: ${{env.deno-version}}
      
      - name: Run Tests
        run: deno task test

      - name: Generate jUnit Report
        uses: mikepenz/action-junit-report@v4
        with:
          report_paths: 'reports/report.xml'

